"""
profile_loader.py
-----------------
Digital Talaria – Profile Loader
200-Runner Marathon Cohort Edition

Provides a validated entry point for loading synthetic runner profiles
from disk. Updated for the 200-runner marathon cohort with full
preference schema (RunnerPreferences).

Usage:
    from src.data_gen.profile_loader import load_profiles

    profiles = load_profiles()                    # all 200
    pa_only  = get_profiles_by_type("PA")         # 40 PA runners
"""

import json
import os
from typing import List, Optional

from src.data_gen.profile_generator import (
    RunnerProfile, RunnerPreferences, MacroRatio,
)

_DEFAULT_PROFILES_PATH = os.path.join("data", "profiles", "profiles.json")
EXPECTED_PROFILE_COUNT = 200


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _dict_to_profile(d: dict) -> RunnerProfile:
    """Reconstruct a RunnerProfile from a JSON-deserialised dictionary."""
    d = dict(d)   # shallow copy -- don't mutate caller's dict

    # Reconstruct MacroRatio
    macro_data = d.pop("macro_ratio")
    macro = MacroRatio(
        carb_pct=macro_data["carb_pct"],
        protein_pct=macro_data["protein_pct"],
        fat_pct=macro_data["fat_pct"],
    )

    # Reconstruct RunnerPreferences
    prefs_data = d.pop("preferences")
    prefs = RunnerPreferences(
        preferred_rest_days_per_week=prefs_data["preferred_rest_days_per_week"],
        preferred_rest_day_slots=prefs_data["preferred_rest_day_slots"],
        flexible_rest_days=prefs_data["flexible_rest_days"],
        excluded_activity_types=prefs_data["excluded_activity_types"],
        excluded_reason=prefs_data["excluded_reason"],
        preferred_max_rpe=prefs_data["preferred_max_rpe"],
        prefers_low_impact=prefs_data["prefers_low_impact"],
        available_days_per_week=prefs_data["available_days_per_week"],
        preferred_long_run_day=prefs_data["preferred_long_run_day"],
        preferred_workout_time=prefs_data["preferred_workout_time"],
        goal_race_distance=prefs_data["goal_race_distance"],
        target_finish_time=prefs_data["target_finish_time"],
        experience_level=prefs_data["experience_level"],
    )

    # Remove derived fields recomputed by __post_init__
    for derived in ("est_hr_max_bpm", "est_hr_max_method", "age_division"):
        d.pop(derived, None)

    # Defensive defaults for fields that may be absent in edge cases.
    # All five performance fields are present in profiles generated by the
    # current profile_generator.py. These guards protect against any
    # profiles.json written before the marathon schema update.
    d.setdefault("prior_5k_time_min",            None)
    d.setdefault("prior_10k_time_min",           None)
    d.setdefault("prior_half_marathon_time_min", None)
    d.setdefault("prior_marathon_time_min",      None)
    # goal_marathon_time_min is always set -- no default needed,
    # but guard against truly malformed files
    if "goal_marathon_time_min" not in d:
        raise ValueError(
            f"Profile dict missing required field 'goal_marathon_time_min'. "
            f"Regenerate profiles.json using profile_generator.py."
        )

    # Backward compatibility: wearable_source added in Phase 1 hardening.
    d.setdefault("wearable_source", None)

    return RunnerProfile(macro_ratio=macro, preferences=prefs, **d)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def load_profiles(path: str = _DEFAULT_PROFILES_PATH) -> List[RunnerProfile]:
    """
    Load and validate all 200 runner profiles from disk.

    Args:
        path: Path to profiles.json.

    Returns:
        List of 200 validated RunnerProfile objects.

    Raises:
        FileNotFoundError: If profiles.json does not exist.
        ValueError: If profile count does not match expected 200.
    """
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Profile dataset not found at '{path}'. "
            "Run: python -m src.data_gen.profile_generator"
        )

    with open(path, "r", encoding="utf-8") as f:
        raw_list = json.load(f)

    profiles = [_dict_to_profile(d) for d in raw_list]

    if len(profiles) != EXPECTED_PROFILE_COUNT:
        raise ValueError(
            f"Expected {EXPECTED_PROFILE_COUNT} profiles, "
            f"loaded {len(profiles)}. Dataset may be incomplete."
        )

    return profiles


def get_pilot_profiles(path: str = _DEFAULT_PROFILES_PATH) -> List[RunnerProfile]:
    """Return profiles marked is_pilot=True."""
    return [p for p in load_profiles(path) if p.is_pilot]


def get_profiles_by_type(
    profile_type: str,
    path: str = _DEFAULT_PROFILES_PATH,
) -> List[RunnerProfile]:
    """Return all profiles of a given type (PA, UW, OW, HS, SD)."""
    valid = {"PA", "UW", "OW", "HS", "SD"}
    if profile_type not in valid:
        raise ValueError(f"profile_type must be one of {valid}")
    return [p for p in load_profiles(path) if p.profile_type == profile_type]


def get_profiles_by_division(
    age_division: str,
    path: str = _DEFAULT_PROFILES_PATH,
) -> List[RunnerProfile]:
    """Return all profiles in a given age division."""
    valid = {"20-29", "30-39", "40-49", "50-59", "60-69"}
    if age_division not in valid:
        raise ValueError(f"age_division must be one of {valid}")
    return [p for p in load_profiles(path) if p.age_division == age_division]


def get_profile_by_id(
    runner_id: str,
    path: str = _DEFAULT_PROFILES_PATH,
) -> Optional[RunnerProfile]:
    """Return a single profile by runner_id, or None if not found."""
    for p in load_profiles(path):
        if p.runner_id == runner_id:
            return p
    return None